language: cpp

# use sed to replace the SSH URL with the public URL, then init and update submodules
before_install:
  - wget http://www.microchip.com/mymicrochip/filehandler.aspx?ddocname=en605750 -O avrtoolchain.tar.gz
  - tar xzf avrtoolchain.tar.gz
  - sudo ln -s $(pwd)/avr8-gnu-toolchain-linux_x86_64 /usr/local/avr
  - PATH=/usr/local/avr/bin:${PATH}
  - export MAKEFLAGS=-j$(nproc)
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - cd src/
  
install:  
  - sudo apt-get install -y srecord
  
script:
  - make clean && make fw_opendeck && \
    make clean && make fw_pro_micro && \
    make clean && make fw_leonardo && \
    make clean && make fw_uno && \
    make clean && make fw_mega && \
    make clean && make fw_16u2 && \
    make clean && make fw_8u2 && \
    make clean && make fw_teensy2pp && \
    make clean && make boot_opendeck && \
    make clean && make boot_leonardo && \
    make clean && make boot_kodama && \
    make clean && make fw_tannin && \
    make clean && make fw_kodama && \
    make clean && make fw_bergamot

# disable the default submodule logic
git:
    submodules: false
  
notifications:
  email:
    on_success: change
    on_failure: change
