language: cpp

before_install:
  - wget https://www.microchip.com/mymicrochip/filehandler.aspx?ddocname=en607660 -O avrtoolchain.tar.gz
  - wget https://apt.llvm.org/llvm-snapshot.gpg.key
  - sudo apt-key add llvm-snapshot.gpg.key
  - sudo add-apt-repository 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
  - sudo apt update
  - git submodule update --init --recursive

install:
  - tar xzf avrtoolchain.tar.gz
  - sudo ln -s $(pwd)/avr8-gnu-toolchain-linux_x86_64/ /usr/local/avr
  - PATH=/usr/local/avr/bin:${PATH}
  - sudo apt-get install -y srecord clang-8 clang-format-8
  - export MAKEFLAGS=-j$(nproc)
  - export CPP=clang-8
  - export CXX=clang++-8

script:
  - cd src/
  - make exe-scripts
  - ../scripts/build_fwbtldr_all.sh
  - cd tests/
  - ../../scripts/build_execute_tests.sh

# disable the default submodule logic
git:
    submodules: false

notifications:
  email:
    on_success: change
    on_failure: change
