---
  symbols:
    - "ARCH=ARCH_AVR8"
    - "__AVR__"
    - "F_CPU=16000000UL"
    - "F_USB=16000000UL"
    - "BOARD=BOARD_NONE"
    - "USE_STATIC_OPTIONS=0"
    - "USB_DEVICE_ONLY"
    - "INTERRUPT_CONTROL_ENDPOINT"
    - "ADC_10_BIT"
    - "ORDERED_EP_CONFIG"
    - "UID_BITS=80"
    - "MEDIAN_SAMPLE_COUNT=3"
    - "MEDIAN_MIDDLE_VALUE=1"