---
  arch: "avr"
  mcuFamily: "avr8"
  define-symbol: "__AVR_ATmega2560__"
  flash:
    app-start: 0x00
    boot-start: 0x3E000
    metadata-start: 0xE4
    page-size: 0x100
    size: 0x40000
  eeprom:
    size: 0x1000
  interfaces:
    uart: 3
    i2c: 1
  fuses:
    unlock: 0xFF
    lock: 0xEF
    ext: 0xFC
    high: 0xD0
    low: 0xFF