---
  arch: "avr"
  mcuFamily: "avr8"
  vendor: "atmel"
  define-symbol: "__AVR_ATmega16U2__"
  flash:
    flash-start: 0x00
    app-start: 0x00
    app-metadata-offset: 0x74
    boot-start: 0x3000
    page-size: 0x80
    size: 0x4000
  eeprom:
    size: 0x200
  peripherals:
    uart: 1
    i2c: 0
  fuses:
    unlock: 0xFF
    lock: 0xEF
    ext: 0xF8
    high: 0xD0
    low: 0xFF
  timers:
    #periods in us
    main:
      period: 1000
      channel: 0