---
  flash:
    boot-start-page: 39
    app-start-page: 47
    app-boot-jump-offset: 4
    emueeprom:
      factory-page:
        page: 88
      page1:
        page: 104
      page2:
        page: 120
  adc:
    # Ignored for nRF52
    prescaler: 1
    # Internal oversampling used, take one sample only
    samples: 1