---
  flash:
    boot-start-page: 0
    app-start-page: 2
    app-boot-jump-offset: 4
    emueeprom:
      factory-page:
        page: 5
        start-offset: 0x10000
      page1:
        page: 6
      page2:
        page: 7
  adc:
    prescaler: 8
    samples: 16