---
  flash:
    boot-start-page: 0
    app-start-page: 5
    app-boot-jump-offset: 4
    emueeprom:
      factory-page:
        page: 2
      page1:
        page: 3
      page2:
        page: 4
  adc:
    prescaler: 4
    samples: 16