---
  arch: "arm"
  mcuFamily: "f4"
  vendor: "st"
  cpu: "cortex-m4"
  fpu: "fpv4-sp-d16"
  float-abi: "hard"
  define-symbol: "STM32F407xx"
  flash:
    flash-start: 0x8000000
    boot-start: 0x8000000
    app-start: 0x8008000
    app-metadata-offset: 0x190
    pages:
    -
      address: 0x8000000
      size: 16384
    -
      address: 0x8004000
      size: 16384
    -
      address: 0x8008000
      size: 16384
    -
      address: 0x800C000
      size: 16384
    -
      address: 0x8010000
      size: 65536
    -
      address: 0x8020000
      size: 131072
    -
      address: 0x8040000
      size: 131072
    -
      address: 0x8060000
      size: 131072
    -
      address: 0x8080000
      size: 131072
    -
      address: 0x80A0000
      size: 131072
    -
      address: 0x80C0000
      size: 131072
    -
      address: 0x80E0000
      size: 131072
  eeprom:
    emulated:
      factory-flash-page: 6
      eeprom-flash-page1: 7
      eeprom-flash-page2: 8
  #PLL values for 84MHz clock
  clocks:
      hse8MHz:
        pllm: 4
        plln: 168
        pllq: 7
        pllp: "RCC_PLLP_DIV2"
        ahb_clk_div : "RCC_SYSCLK_DIV2"
        apb1_clk_div: "RCC_HCLK_DIV2"
        apb2_clk_div: "RCC_HCLK_DIV1"
      hse12MHz:
        pllm: 6
        plln: 168
        pllq: 7
        pllp: "RCC_PLLP_DIV2"
        ahb_clk_div : "RCC_SYSCLK_DIV2"
        apb1_clk_div: "RCC_HCLK_DIV2"
        apb2_clk_div: "RCC_HCLK_DIV1"
      hse16MHz:
        pllm: 8
        plln: 168
        pllq: 7
        pllp: "RCC_PLLP_DIV2"
        ahb_clk_div : "RCC_SYSCLK_DIV2"
        apb1_clk_div: "RCC_SYSCLK_DIV2"
        apb2_clk_div: "RCC_SYSCLK_DIV1"
      hse25MHz:
        pllm: 25
        plln: 336
        pllq: 7
        pllp: "RCC_PLLP_DIV2"
        ahb_clk_div : "RCC_SYSCLK_DIV2"
        apb1_clk_div: "RCC_SYSCLK_DIV2"
        apb2_clk_div: "RCC_SYSCLK_DIV1"
  voltage_scale: "PWR_REGULATOR_VOLTAGE_SCALE1"
  peripherals:
    uart: 6
    i2c: 3
  timers:
    #periods in us
    main:
      period: 1000
      channel: 0
    pwm:
      period: 200
      channel: 1