---
  mcu: "stm32f411ce"
  extClockMhz: 25
  usb: true
  dinMIDI:
    uartChannel: 0
  buttons:
    type: "native"
    extPullups: false
    pins:
    -
      port: "B"
      index: 12
  analog:
    type: "4067"
    multiplexers: 2
    pins:
      s0:
        port: "A"
        index: 5
      s1:
        port: "A"
        index: 6
      s2:
        port: "A"
        index: 7
      s3:
        port: "B"
        index: 0
      z0:
        port: "A"
        index: 1
      z1:
        port: "A"
        index: 2
  leds:
    external:
      type: "native"
      pins:
      -
        port: "B"
        index: 9
  bootloader:
    button:
      port: "A"
      index: 0