---
  mcu: "atmega16u2"
  boardNameOverride: "mega2560"
  usb: true
  leds:
    internal:
      invert: true
      pins:
        din:
          rx:
            port: "D"
            index: 4
          tx:
            port: "D"
            index: 5
        usb:
          rx:
            port: "D"
            index: 4
          tx:
            port: "D"
            index: 5
  usbLink:
    type: "host"
    uartChannel: 0