---
  mcu: "stm32f405rg"
  extClockMhz: 12
  usb: true
  dinMIDI:
    uartChannel: 5
  dmx:
    uartChannel: 5
  i2c:
    channel: 0
  touchscreen:
    uartChannel: 5
    components: 64
  buttons:
    type: "native"
    extPullups: false
    pins:
    -
      port: "B"
      index: 8
    -
      port: "B"
      index: 9
    -
      port: "B"
      index: 12
    -
      port: "B"
      index: 13
    -
      port: "B"
      index: 11
    -
      port: "B"
      index: 10
    -
      port: "C"
      index: 13
    -
      port: "B"
      index: 3
  analog:
    type: "native"
    pins:
    -
      port: "A"
      index: 0
    -
      port: "A"
      index: 1
    -
      port: "A"
      index: 2
    -
      port: "A"
      index: 3
    -
      port: "A"
      index: 4
    -
      port: "A"
      index: 5
    -
      port: "A"
      index: 6
    -
      port: "A"
      index: 7
    -
      port: "B"
      index: 0
    -
      port: "B"
      index: 1
    -
      port: "C"
      index: 0
    -
      port: "C"
      index: 1
    -
      port: "C"
      index: 2
    -
      port: "C"
      index: 3
    -
      port: "C"
      index: 4
    -
      port: "C"
      index: 5
  leds:
    internal:
      pins:
        din:
          rx:
            port: "B"
            index: 4
          tx:
            port: "A"
            index: 15
        usb:
          rx:
            port: "A"
            index: 14
          tx:
            port: "A"
            index: 13
    external:
      type: "native"
      pins:
      -
        port: "B"
        index: 14
      -
        port: "B"
        index: 15