---
flash:
  args: "FLASH_TOOL=bmp PORT=bmp_opendeck22"
dinMidi:
  in: "ESI M4U eX MIDI 7"
  out: "ESI M4U eX MIDI 8"
io:
  analog-pins:
  - 15
  - 16
  analog-id:
  - 0
  - 31
  led-pins:
  - 4
  - 5
  led-id:
  - 0
  - 47