name: Deploy UI

on: [repository_dispatch]

jobs:
  build:
    name: Deploy UI
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: webui
      - name: Prepare build env
        run: |
          sudo apt install yarn
      - name: Deploy new UI
        run: |
          git config --global user.name "webui_bot"
          git config --global user.email "2544094+webui_bot@users.noreply.github.com"
          git clone https://github.com/paradajz/OpenDeckUI.git
          rm -rf _assets index.html
          cd OpenDeckUI
          yarn
          yarn build
          cd ../
          mv OpenDeckUI/dist/* .
          git add index.html _assets*
          git commit --allow-empty -m "update webui"
          git push https://github.com/paradajz/OpenDeck.git webui
