name: CI [Linux]

on: [push]

jobs:
  build_and_test:
    name: Build and test all targets
    runs-on: ubuntu-20.04
    container:
      image: paradajz168/opendeck-dev:latest
      options: --user root
    steps:
      - name: Pull the repository and submodules
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Build targets
        run: |
          git fetch --tags
          cd src/
          ../scripts/build_targets.sh
      - name: Test targets
        run: |
          cd tests/
          ../scripts/build_targets.sh
          make exec
  hw-tests:
    name: Run tests on physical boards
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Run tests on hardware
        run: |
          git reset --hard
          git clean -dxf
          git fetch --tags
          cd tests
          ../scripts/build_targets.sh --hw
          make exec HW_TESTING=1