name: Code formatting

on: [push]

jobs:
  format:
    name: Code formatting
    runs-on: ubuntu-20.04
    steps:
       - name: Pull the repository
         uses: actions/checkout@v1
         with:
          submodules: true
       - name: Prepare env
         run: |
           sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
           sudo apt install clang-format-11
           curl -L https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_amd64 > yq
           chmod +x yq
           sudo mv yq /usr/local/bin/yq
       - name: Format
         run: |
           clang-format --version
           cd src
           make format CF_FAIL_ON_DIFF=1 CLANG_FORMAT=clang-format-11
           cd ../tests
           make format CF_FAIL_ON_DIFF=1 CLANG_FORMAT=clang-format-11
