name: Code formatting

on: [push]

jobs:
  format:
    name: Code formatting
    runs-on: ubuntu-20.04
    steps:
       - name: Pull the repository
         uses: actions/checkout@v1
         with:
          submodules: true
       - name: Prepare env
         run: |
           sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
           sudo apt install clang-format-11
           sudo touch /usr/bin/avrdude && sudo chmod +x /usr/bin/avrdude
           sudo touch /usr/bin/srec_cat && sudo chmod +x /usr/bin/srec_cat
           sudo touch /usr/bin/avr-gcc && sudo chmod +x /usr/bin/avr-gcc
           sudo touch /usr/bin/avr-g++ && sudo chmod +x /usr/bin/avr-g++
           sudo touch /usr/bin/arm-none-eabi-gcc && sudo chmod +x /usr/bin/arm-none-eabi-gcc
           sudo touch /usr/bin/arm-none-eabi-g++ && sudo chmod +x /usr/bin/arm-none-eabi-g++
           sudo touch /usr/bin/gdb && sudo chmod +x /usr/bin/gdb
           curl -s https://api.github.com/repos/tomwright/dasel/releases/latest | grep browser_download_url | grep linux_amd64 | cut -d '"' -f 4 | wget -qi -
           chmod +x dasel_linux_amd64
           sudo mv dasel_linux_amd64 /usr/local/bin/dasel
       - name: Format
         run: |
           clang-format --version
           cd src
           make format CF_FAIL_ON_DIFF=1 CLANG_FORMAT=clang-format-11
           cd ../tests
           make format CF_FAIL_ON_DIFF=1 CLANG_FORMAT=clang-format-11
