name: Test [Linux]

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
       - name: Pull the repository and submodules
         uses: actions/checkout@v1
         with:
          submodules: true
       - name: Prepare build env
         run: |
           wget https://apt.llvm.org/llvm-snapshot.gpg.key
           sudo apt-key add llvm-snapshot.gpg.key
           sudo add-apt-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
           sudo apt update
           sudo apt-get install -y clang-9 ctags jq
           sudo touch /usr/bin/avrdude && sudo chmod +x /usr/bin/avrdude
           curl -L https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_amd64 > yq
           chmod +x yq
           sudo mv yq /usr/local/bin/yq
       - name: Build
         run: |
           C_COMPILER=clang-9
           CPP_COMPILER=clang++-9
           cd tests/
           ../scripts/build_targets.sh --type=tests
           make exec