name: Firmware build [macOS]

on: [push]

jobs:
  build:
    name: Firmware build
    runs-on: macos-latest
    steps:
      - name: Pull the repository and submodules
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Prepare build env
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          brew tap osx-cross/avr
          brew install wget avr-gcc coreutils findutils srecord jq yq imagemagick
          wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2019q4/gcc-arm-none-eabi-9-2019-q4-major-mac.tar.bz2 -O armtoolchain.tar.bz2
          tar xjf armtoolchain.tar.bz2
      - name: Build
        run: |
          PATH=$(pwd)/gcc-arm-none-eabi-9-2019-q4-major/bin:${PATH}
          cd src/
          ../scripts/build_targets.sh --type=fw_all