name: Deploy

on:
  release:
    types: [created]

jobs:
  build:
    name: Attach SysEx firmware to release
    runs-on: ubuntu-20.04
    steps:
      - name: Pull the repository and submodules
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Prepare build env
        run: |
          sudo apt-get install -y srecord avr-libc gcc-avr gcc-arm-none-eabi
          sudo touch /usr/bin/avrdude && sudo chmod +x /usr/bin/avrdude
          sudo touch /usr/bin/gdb && sudo chmod +x /usr/bin/gdb
          curl -s https://api.github.com/repos/tomwright/dasel/releases/latest | grep browser_download_url | grep linux_amd64 | cut -d '"' -f 4 | wget -qi -
          chmod +x dasel_linux_amd64
          sudo mv dasel_linux_amd64 /usr/local/bin/dasel
          wget https://downloads.arduino.cc/arduino-1.8.13-linux64.tar.xz -O arduino.tar.xz
          tar -xf arduino.tar.xz
      - name: Build
        run: |
          PATH=$(pwd)/arduino-1.8.13/hardware/tools/avr/bin:${PATH}
          cd src/
          ../scripts/build_targets.sh --type=fw_release
      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name="${GITHUB_REF##*/}"
          hub release edit $(find ./src/build/merged -type f -name "*.sysex" -printf "-a %p ") -m "" "$tag_name"
          hub release edit $(find ./src/build/merged -type f -name "*.hex" -printf "-a %p ") -m "" "$tag_name"
          hub release edit $(find ./src/build/merged -type f -name "*.bin" -printf "-a %p ") -m "" "$tag_name"