name: Testing

on: [push]

jobs:
  virtual:
    runs-on: ubuntu-20.04
    steps:
       - uses: actions/checkout@v2
         with:
          fetch-depth: 0
          submodules: true
       - name: Prepare build env
         run: |
           sudo apt update
           sudo apt-get install -y clang ctags
           sudo touch /usr/bin/avrdude && sudo chmod +x /usr/bin/avrdude
           sudo touch /usr/bin/srec_cat && sudo chmod +x /usr/bin/srec_cat
           sudo touch /usr/bin/avr-gcc && sudo chmod +x /usr/bin/avr-gcc
           sudo touch /usr/bin/avr-g++ && sudo chmod +x /usr/bin/avr-g++
           sudo touch /usr/bin/arm-none-eabi-gcc && sudo chmod +x /usr/bin/arm-none-eabi-gcc
           sudo touch /usr/bin/arm-none-eabi-g++ && sudo chmod +x /usr/bin/arm-none-eabi-g++
           sudo touch /usr/bin/gdb && sudo chmod +x /usr/bin/gdb
           curl -s https://api.github.com/repos/tomwright/dasel/releases/latest | grep browser_download_url | grep linux_amd64 | cut -d '"' -f 4 | wget -qi -
           chmod +x dasel_linux_amd64
           sudo mv dasel_linux_amd64 /usr/local/bin/dasel
       - name: Build
         run: |
           cd tests/
           ../scripts/build_targets.sh --type=tests
           make exec
  hardware:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
    - name: Run tests on hardware
      run: |
        git reset --hard
        git clean -dxf
        git fetch --tags
        cd tests
        ../scripts/build_targets.sh --type=tests --hw
        make exec HW_TESTING=1